#pragma once
// IWYU pragma private; include "System/Data/ConstraintCollection.hpp"
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "../../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/Data/zzzz__InternalDataCollectionBase_def.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(ConstraintCollection)
namespace System::Collections {
class ArrayList;
}
namespace System::ComponentModel {
class CollectionChangeEventArgs;
}
namespace System::ComponentModel {
class CollectionChangeEventHandler;
}
namespace System::Data {
class Constraint;
}
namespace System::Data {
class DataColumn;
}
namespace System::Data {
class DataTable;
}
namespace System::Data {
class ForeignKeyConstraint;
}
namespace System::Data {
class UniqueConstraint;
}
// Forward declare root types
namespace System::Data {
class ConstraintCollection;
}
// Write type traits
MARK_REF_PTR_T(::System::Data::ConstraintCollection);
// Dependencies System.Data.InternalDataCollectionBase
namespace System::Data {
// Is value type: false
// CS Name: System.Data.ConstraintCollection
class CORDL_TYPE ConstraintCollection : public ::System::Data::InternalDataCollectionBase {
public:
  // Declarations
  __declspec(property(get = get_Item)) ::System::Data::Constraint* Item[];

  __declspec(property(get = get_Item)) ::System::Data::Constraint* Item[];

  __declspec(property(get = get_List)) ::System::Collections::ArrayList* List;

  __declspec(property(get = get_Table)) ::System::Data::DataTable* Table;

  /// @brief Field _defaultNameIndex, offset 0x20, size 0x4
  __declspec(property(get = __cordl_internal_get__defaultNameIndex, put = __cordl_internal_set__defaultNameIndex)) int32_t _defaultNameIndex;

  /// @brief Field _delayLoadingConstraints, offset 0x30, size 0x8
  __declspec(property(get = __cordl_internal_get__delayLoadingConstraints,
                      put = __cordl_internal_set__delayLoadingConstraints)) ::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*>
      _delayLoadingConstraints;

  /// @brief Field _fLoadForeignKeyConstraintsOnly, offset 0x38, size 0x1
  __declspec(property(get = __cordl_internal_get__fLoadForeignKeyConstraintsOnly, put = __cordl_internal_set__fLoadForeignKeyConstraintsOnly)) bool _fLoadForeignKeyConstraintsOnly;

  /// @brief Field _list, offset 0x18, size 0x8
  __declspec(property(get = __cordl_internal_get__list, put = __cordl_internal_set__list)) ::System::Collections::ArrayList* _list;

  /// @brief Field _onCollectionChanged, offset 0x28, size 0x8
  __declspec(property(get = __cordl_internal_get__onCollectionChanged, put = __cordl_internal_set__onCollectionChanged)) ::System::ComponentModel::CollectionChangeEventHandler* _onCollectionChanged;

  /// @brief Field _table, offset 0x10, size 0x8
  __declspec(property(get = __cordl_internal_get__table, put = __cordl_internal_set__table)) ::System::Data::DataTable* _table;

  /// @brief Method Add, addr 0x4157798, size 0xa8, virtual false, abstract: false, final false
  inline ::System::Data::Constraint* Add(::StringW name, ::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> columns, bool primaryKey);

  /// @brief Method Add, addr 0x4156e0c, size 0x8, virtual false, abstract: false, final false
  inline void Add(::System::Data::Constraint* constraint);

  /// @brief Method Add, addr 0x4156e14, size 0x3b4, virtual false, abstract: false, final false
  inline void Add(::System::Data::Constraint* constraint, bool addUniqueWhenAddingForeign);

  /// @brief Method AddForeignKeyConstraint, addr 0x4157600, size 0x70, virtual false, abstract: false, final false
  inline void AddForeignKeyConstraint(::System::Data::ForeignKeyConstraint* constraint);

  /// @brief Method AddUniqueConstraint, addr 0x41573f4, size 0xdc, virtual false, abstract: false, final false
  inline void AddUniqueConstraint(::System::Data::UniqueConstraint* constraint);

  /// @brief Method ArrayAdd, addr 0x4157738, size 0x38, virtual false, abstract: false, final false
  inline void ArrayAdd(::System::Data::Constraint* constraint);

  /// @brief Method ArrayRemove, addr 0x4157840, size 0x38, virtual false, abstract: false, final false
  inline void ArrayRemove(::System::Data::Constraint* constraint);

  /// @brief Method AssignName, addr 0x41575dc, size 0x24, virtual false, abstract: false, final false
  inline ::StringW AssignName();

  /// @brief Method AutoGenerated, addr 0x4157324, size 0xd0, virtual false, abstract: false, final false
  inline bool AutoGenerated(::System::Data::Constraint* constraint);

  /// @brief Method BaseAdd, addr 0x4157670, size 0xc8, virtual false, abstract: false, final false
  inline void BaseAdd(::System::Data::Constraint* constraint);

  /// @brief Method BaseGroupSwitch, addr 0x4157930, size 0x1b4, virtual false, abstract: false, final false
  inline void BaseGroupSwitch(::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*> oldArray, int32_t oldLength,
                              ::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*> newArray, int32_t newLength);

  /// @brief Method BaseRemove, addr 0x4157ae4, size 0x294, virtual false, abstract: false, final false
  inline void BaseRemove(::System::Data::Constraint* constraint);

  /// @brief Method CanRemove, addr 0x4157d78, size 0x30, virtual false, abstract: false, final false
  inline bool CanRemove(::System::Data::Constraint* constraint, bool fThrowException);

  /// @brief Method Clear, addr 0x4157da8, size 0x3d0, virtual false, abstract: false, final false
  inline void Clear();

  /// @brief Method CompareArrays, addr 0x415828c, size 0x88, virtual false, abstract: false, final false
  static inline bool CompareArrays(::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> a1, ::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> a2);

  /// @brief Method Contains, addr 0x4158178, size 0x18, virtual false, abstract: false, final false
  inline bool Contains(::StringW name);

  /// @brief Method Contains, addr 0x4158190, size 0xfc, virtual false, abstract: false, final false
  inline bool Contains(::StringW name, bool caseSensitive);

  /// @brief Method FindConstraint, addr 0x41571c8, size 0x15c, virtual false, abstract: false, final false
  inline ::System::Data::Constraint* FindConstraint(::System::Data::Constraint* constraint);

  /// @brief Method FindForeignKeyConstraint, addr 0x4158420, size 0x130, virtual false, abstract: false, final false
  inline ::System::Data::ForeignKeyConstraint* FindForeignKeyConstraint(::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> parentColumns,
                                                                        ::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> childColumns);

  /// @brief Method FindKeyConstraint, addr 0x4158314, size 0x10c, virtual false, abstract: false, final false
  inline ::System::Data::UniqueConstraint* FindKeyConstraint(::System::Data::DataColumn* column);

  /// @brief Method FindKeyConstraint, addr 0x41574d0, size 0x10c, virtual false, abstract: false, final false
  inline ::System::Data::UniqueConstraint* FindKeyConstraint(::ArrayW<::System::Data::DataColumn*, ::Array<::System::Data::DataColumn*>*> columns);

  /// @brief Method InternalIndexOf, addr 0x4156cb0, size 0x15c, virtual false, abstract: false, final false
  inline int32_t InternalIndexOf(::StringW constraintName);

  /// @brief Method MakeName, addr 0x4157878, size 0xb8, virtual false, abstract: false, final false
  inline ::StringW MakeName(int32_t index);

  static inline ::System::Data::ConstraintCollection* New_ctor(::System::Data::DataTable* table);

  /// @brief Method OnCollectionChanged, addr 0x4157770, size 0x28, virtual false, abstract: false, final false
  inline void OnCollectionChanged(::System::ComponentModel::CollectionChangeEventArgs* ccevent);

  /// @brief Method RegisterName, addr 0x41564dc, size 0x1e8, virtual false, abstract: false, final false
  inline void RegisterName(::StringW name);

  /// @brief Method Remove, addr 0x4158550, size 0x15c, virtual false, abstract: false, final false
  inline void Remove(::System::Data::Constraint* constraint);

  /// @brief Method UnregisterName, addr 0x41566c4, size 0x80, virtual false, abstract: false, final false
  inline void UnregisterName(::StringW name);

  constexpr int32_t const& __cordl_internal_get__defaultNameIndex() const;

  constexpr int32_t& __cordl_internal_get__defaultNameIndex();

  constexpr ::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*> const& __cordl_internal_get__delayLoadingConstraints() const;

  constexpr ::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*>& __cordl_internal_get__delayLoadingConstraints();

  constexpr bool const& __cordl_internal_get__fLoadForeignKeyConstraintsOnly() const;

  constexpr bool& __cordl_internal_get__fLoadForeignKeyConstraintsOnly();

  constexpr ::System::Collections::ArrayList* const& __cordl_internal_get__list() const;

  constexpr ::System::Collections::ArrayList*& __cordl_internal_get__list();

  constexpr ::System::ComponentModel::CollectionChangeEventHandler* const& __cordl_internal_get__onCollectionChanged() const;

  constexpr ::System::ComponentModel::CollectionChangeEventHandler*& __cordl_internal_get__onCollectionChanged();

  constexpr ::System::Data::DataTable* const& __cordl_internal_get__table() const;

  constexpr ::System::Data::DataTable*& __cordl_internal_get__table();

  constexpr void __cordl_internal_set__defaultNameIndex(int32_t value);

  constexpr void __cordl_internal_set__delayLoadingConstraints(::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*> value);

  constexpr void __cordl_internal_set__fLoadForeignKeyConstraintsOnly(bool value);

  constexpr void __cordl_internal_set__list(::System::Collections::ArrayList* value);

  constexpr void __cordl_internal_set__onCollectionChanged(::System::ComponentModel::CollectionChangeEventHandler* value);

  constexpr void __cordl_internal_set__table(::System::Data::DataTable* value);

  /// @brief Method .ctor, addr 0x4156a18, size 0xa0, virtual false, abstract: false, final false
  inline void _ctor(::System::Data::DataTable* table);

  /// @brief Method get_Item, addr 0x4156ac0, size 0xfc, virtual false, abstract: false, final false
  inline ::System::Data::Constraint* get_Item(int32_t index);

  /// @brief Method get_Item, addr 0x4156bc4, size 0xec, virtual false, abstract: false, final false
  inline ::System::Data::Constraint* get_Item(::StringW name);

  /// @brief Method get_List, addr 0x4156ab8, size 0x8, virtual true, abstract: false, final false
  inline ::System::Collections::ArrayList* get_List();

  /// @brief Method get_Table, addr 0x4156bbc, size 0x8, virtual false, abstract: false, final false
  inline ::System::Data::DataTable* get_Table();

protected:
  // Ctor Parameters []
  // @brief default ctor
  constexpr ConstraintCollection();

public:
  // Ctor Parameters [CppParam { name: "", ty: "ConstraintCollection", modifiers: "&&", def_value: None }]
  // @brief delete move ctor to prevent accidental deref moves
  ConstraintCollection(ConstraintCollection&&) = delete;

  // Ctor Parameters [CppParam { name: "", ty: "ConstraintCollection", modifiers: "const&", def_value: None }]
  // @brief delete copy ctor to prevent accidental deref copies
  ConstraintCollection(ConstraintCollection const&) = delete;

  /// @brief IL2CPP Metadata Type Index
  static constexpr uint32_t __IL2CPP_TYPE_DEFINITION_INDEX{ 11370 };

  /// @brief Field _table, offset: 0x10, size: 0x8, def value: None
  ::System::Data::DataTable* ____table;

  /// @brief Field _list, offset: 0x18, size: 0x8, def value: None
  ::System::Collections::ArrayList* ____list;

  /// @brief Field _defaultNameIndex, offset: 0x20, size: 0x4, def value: None
  int32_t ____defaultNameIndex;

  /// @brief Field _onCollectionChanged, offset: 0x28, size: 0x8, def value: None
  ::System::ComponentModel::CollectionChangeEventHandler* ____onCollectionChanged;

  /// @brief Field _delayLoadingConstraints, offset: 0x30, size: 0x8, def value: None
  ::ArrayW<::System::Data::Constraint*, ::Array<::System::Data::Constraint*>*> ____delayLoadingConstraints;

  /// @brief Field _fLoadForeignKeyConstraintsOnly, offset: 0x38, size: 0x1, def value: None
  bool ____fLoadForeignKeyConstraintsOnly;

  static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::System::Data::ConstraintCollection, ____table) == 0x10, "Offset mismatch!");

static_assert(offsetof(::System::Data::ConstraintCollection, ____list) == 0x18, "Offset mismatch!");

static_assert(offsetof(::System::Data::ConstraintCollection, ____defaultNameIndex) == 0x20, "Offset mismatch!");

static_assert(offsetof(::System::Data::ConstraintCollection, ____onCollectionChanged) == 0x28, "Offset mismatch!");

static_assert(offsetof(::System::Data::ConstraintCollection, ____delayLoadingConstraints) == 0x30, "Offset mismatch!");

static_assert(offsetof(::System::Data::ConstraintCollection, ____fLoadForeignKeyConstraintsOnly) == 0x38, "Offset mismatch!");

static_assert(::cordl_internals::size_check_v<::System::Data::ConstraintCollection, 0x40>, "Size mismatch!");

} // namespace System::Data
NEED_NO_BOX(::System::Data::ConstraintCollection);
DEFINE_IL2CPP_ARG_TYPE(::System::Data::ConstraintCollection*, "System.Data", "ConstraintCollection");
