#ifdef __cpp_modules
module;
#endif

#pragma once
#include "UnityEngine/VFX/EventAttribute.hpp"
#include "UnityEngine/VFX/EventAttributeBool.hpp"
#include "UnityEngine/VFX/EventAttributeColor.hpp"
#include "UnityEngine/VFX/EventAttributeFloat.hpp"
#include "UnityEngine/VFX/EventAttributeInt.hpp"
#include "UnityEngine/VFX/EventAttributeUInt.hpp"
#include "UnityEngine/VFX/EventAttributeValue_1.hpp"
#include "UnityEngine/VFX/EventAttributeVector2.hpp"
#include "UnityEngine/VFX/EventAttributeVector3.hpp"
#include "UnityEngine/VFX/EventAttributeVector4.hpp"
#include "UnityEngine/VFX/EventAttributes.hpp"
#include "UnityEngine/VFX/IncrementStripIndexOnStart.hpp"
#include "UnityEngine/VFX/LoopAndDelay.hpp"
#include "UnityEngine/VFX/PlayableTimeSpace.hpp"
#include "UnityEngine/VFX/SetSpawnTime.hpp"
#include "UnityEngine/VFX/SpawnOverDistance.hpp"
#include "UnityEngine/VFX/VFXBatchInfo.hpp"
#include "UnityEngine/VFX/VFXBatchedEffectInfo.hpp"
#include "UnityEngine/VFX/VFXCameraBufferTypes.hpp"
#include "UnityEngine/VFX/VFXCameraXRSettings.hpp"
#include "UnityEngine/VFX/VFXEventAttribute.hpp"
#include "UnityEngine/VFX/VFXExpressionValues.hpp"
#include "UnityEngine/VFX/VFXManager.hpp"
#include "UnityEngine/VFX/VFXOutputEventArgs.hpp"
#include "UnityEngine/VFX/VFXRuntimeResources.hpp"
#include "UnityEngine/VFX/VFXSpace.hpp"
#include "UnityEngine/VFX/VFXSpawnerCallbacks.hpp"
#include "UnityEngine/VFX/VFXSpawnerLoopState.hpp"
#include "UnityEngine/VFX/VFXSpawnerState.hpp"
#include "UnityEngine/VFX/VFXTimeSpaceHelper.hpp"
#include "UnityEngine/VFX/VFXTypeAttribute.hpp"
#include "UnityEngine/VFX/VisualEffect.hpp"
#include "UnityEngine/VFX/VisualEffectAsset.hpp"
#include "UnityEngine/VFX/VisualEffectControlClip.hpp"
#include "UnityEngine/VFX/VisualEffectControlPlayableBehaviour.hpp"
#include "UnityEngine/VFX/VisualEffectControlTrack.hpp"
#include "UnityEngine/VFX/VisualEffectControlTrackController.hpp"
#include "UnityEngine/VFX/VisualEffectControlTrackMixerBehaviour.hpp"
#include "UnityEngine/VFX/VisualEffectObject.hpp"
#include "UnityEngine/VFX/VisualEffectPlayableSerializedEvent.hpp"
#include "UnityEngine/VFX/VisualEffectPlayableSerializedEventNoColor.hpp"
#ifdef __cpp_modules
export module VFX;
#endif
