#pragma once
#include "BeatmapSaveDataVersion2_6_0AndEarlier/zzzz__SpecialEventsForKeyword_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "BeatmapSaveDataVersion2_6_0AndEarlier/zzzz__SpecialEventsForKeyword_impl.hpp"
#endif
