#ifdef __cpp_modules
module;
#endif

#pragma once
#include "UnityEngine/Audio/AudioClipPlayable.hpp"
#include "UnityEngine/Audio/AudioContainerElement.hpp"
#include "UnityEngine/Audio/AudioFormat.hpp"
#include "UnityEngine/Audio/AudioManagerTestProxy.hpp"
#include "UnityEngine/Audio/AudioMixer.hpp"
#include "UnityEngine/Audio/AudioMixerGroup.hpp"
#include "UnityEngine/Audio/AudioMixerPlayable.hpp"
#include "UnityEngine/Audio/AudioMixerSnapshot.hpp"
#include "UnityEngine/Audio/AudioMixerUpdateMode.hpp"
#include "UnityEngine/Audio/AudioPlayableBinding.hpp"
#include "UnityEngine/Audio/AudioPlayableGraphExtensions.hpp"
#include "UnityEngine/Audio/AudioPlayableOutput.hpp"
#include "UnityEngine/Audio/AudioRandomContainer.hpp"
#include "UnityEngine/Audio/AudioRandomContainerAutomaticTriggerMode.hpp"
#include "UnityEngine/Audio/AudioRandomContainerLoopMode.hpp"
#include "UnityEngine/Audio/AudioRandomContainerPlaybackMode.hpp"
#include "UnityEngine/Audio/AudioRandomContainerTriggerMode.hpp"
#include "UnityEngine/Audio/AudioResource.hpp"
#include "UnityEngine/Audio/ChannelBuffer.hpp"
#include "UnityEngine/Audio/ConfigureArguments.hpp"
#include "UnityEngine/Audio/ControlContext.hpp"
#include "UnityEngine/Audio/ControlFunction.hpp"
#include "UnityEngine/Audio/ControlHeader.hpp"
#include "UnityEngine/Audio/DSPConfiguration.hpp"
#include "UnityEngine/Audio/DisposeArguments.hpp"
#include "UnityEngine/Audio/Generator.hpp"
#include "UnityEngine/Audio/GeneratorInstance.hpp"
#include "UnityEngine/Audio/IAudioGenerator.hpp"
#include "UnityEngine/Audio/IAudioScriptingContext.hpp"
#include "UnityEngine/Audio/IGeneratorControlExtensions.hpp"
#include "UnityEngine/Audio/IGeneratorDefinition.hpp"
#include "UnityEngine/Audio/IGeneratorProcessorExtensions.hpp"
#include "UnityEngine/Audio/IRootOutputControlExtensions.hpp"
#include "UnityEngine/Audio/IRootOutputProcessorExtensions.hpp"
#include "UnityEngine/Audio/MessageArguments.hpp"
#include "UnityEngine/Audio/MessageExtensions.hpp"
#include "UnityEngine/Audio/ProcessingContext.hpp"
#include "UnityEngine/Audio/Processor.hpp"
#include "UnityEngine/Audio/ProcessorExtensions.hpp"
#include "UnityEngine/Audio/ProcessorFunction.hpp"
#include "UnityEngine/Audio/ProcessorHeader.hpp"
#include "UnityEngine/Audio/ProcessorInstance.hpp"
#include "UnityEngine/Audio/ProcessorRealtimeUpdateArguments.hpp"
#include "UnityEngine/Audio/RealtimeAccess.hpp"
#include "UnityEngine/Audio/RealtimeContext.hpp"
#include "UnityEngine/Audio/RootOutputInstance.hpp"
#include "UnityEngine/Audio/ScriptableGeneratorBindings.hpp"
#include "UnityEngine/Audio/ScriptableProcessorBindings.hpp"
#include "UnityEngine/Audio/UpdateArguments.hpp"
#ifdef __cpp_modules
export module Audio;
#endif
