#pragma once
#include "GlobalNamespace/zzzz__AnnotatedBeatmapLevelCollectionsGridViewAnimator_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__AnnotatedBeatmapLevelCollectionsGridViewAnimator_impl.hpp"
#endif
