#pragma once
#include "GlobalNamespace/zzzz__AppInitScenesTransitionSetupDataContainerSO_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__AppInitScenesTransitionSetupDataContainerSO_impl.hpp"
#endif
