#pragma once
#include "GlobalNamespace/zzzz__BeatmapDifficultySegmentedControlController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__BeatmapDifficultySegmentedControlController_impl.hpp"
#endif
