#pragma once
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundNonLightDynamicRenderer_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundNonLightDynamicRenderer_impl.hpp"
#endif
