#pragma once
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundColorsGradientElementWithLightId_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundColorsGradientElementWithLightId_impl.hpp"
#endif
