#pragma once
#include "GlobalNamespace/zzzz__DeeplinkManagerToDestinationRequestManagerAdapter_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__DeeplinkManagerToDestinationRequestManagerAdapter_impl.hpp"
#endif
