#pragma once
#include "GlobalNamespace/zzzz__FadeOutSongPreviewPlayerOnSceneTransitionStart_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__FadeOutSongPreviewPlayerOnSceneTransitionStart_impl.hpp"
#endif
