#pragma once
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerBeatmapObjectManager_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerBeatmapObjectManager_impl.hpp"
#endif
