#pragma once
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerBombNoteController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerBombNoteController_impl.hpp"
#endif
