#pragma once
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerGameNoteController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerGameNoteController_impl.hpp"
#endif
