#pragma once
#include "GlobalNamespace/zzzz__MultiplayerLocalActiveCenterRingLightsController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__MultiplayerLocalActiveCenterRingLightsController_impl.hpp"
#endif
