#pragma once
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerObstacleClippingController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__MultiplayerConnectedPlayerObstacleClippingController_impl.hpp"
#endif
