#pragma once
#include "GlobalNamespace/zzzz__NoTransitionToggleSelectableStateController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__NoTransitionToggleSelectableStateController_impl.hpp"
#endif
