#pragma once
#include "GlobalNamespace/zzzz__NoTransitionButtonSelectableStateController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__NoTransitionButtonSelectableStateController_impl.hpp"
#endif
