#pragma once
#include "GlobalNamespace/zzzz__OVRMixedRealityCaptureConfigurationExtensions_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__OVRMixedRealityCaptureConfigurationExtensions_impl.hpp"
#endif
