#pragma once
#include "GlobalNamespace/zzzz__PlayerSpecificSettingsAtStartNetSerializable_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__PlayerSpecificSettingsAtStartNetSerializable_impl.hpp"
#endif
