#pragma once
#include "GlobalNamespace/zzzz__PlayerLobbyPermissionConfigurationNetSerializable_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__PlayerLobbyPermissionConfigurationNetSerializable_impl.hpp"
#endif
