#pragma once
#include "GlobalNamespace/zzzz__RecordingToolSettingsNoTransitionInstaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__RecordingToolSettingsNoTransitionInstaller_impl.hpp"
#endif
