#pragma once
#include "GlobalNamespace/zzzz__SafeAreaFocusedSimpleDialogPromptViewController_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "GlobalNamespace/zzzz__SafeAreaFocusedSimpleDialogPromptViewController_impl.hpp"
#endif
