#pragma once
// IWYU pragma private; include "GlobalNamespace/OVRCustomFaceExtensions.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/arrayw.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
CORDL_MODULE_EXPORT(OVRCustomFaceExtensions)
namespace GlobalNamespace {
class OVRCustomFace;
}
namespace GlobalNamespace {
struct OVRFaceExpressions_FaceExpression;
}
namespace System::Collections::Generic {
template <typename T> class HashSet_1;
}
namespace UnityEngine {
class Mesh;
}
// Forward declare root types
namespace GlobalNamespace {
class OVRCustomFaceExtensions;
}
// Write type traits
MARK_REF_T(::GlobalNamespace::OVRCustomFaceExtensions*);
DEFINE_IL2CPP_CLASS(::GlobalNamespace::OVRCustomFaceExtensions*, "", "OVRCustomFaceExtensions");
// Dependencies System.Object
namespace GlobalNamespace {
// Is value type: false
// CS Name: OVRCustomFaceExtensions
class CORDL_TYPE OVRCustomFaceExtensions : public ::System::Object {
public:
  // Declarations
  /// @brief Method AutoGenerateMapping, addr 0x5ef5f70, size 0x298, virtual false, abstract: false, final false
  static inline ::ArrayW<::GlobalNamespace::OVRFaceExpressions_FaceExpression> AutoGenerateMapping(::UnityEngine::Mesh* skinnedMesh, ::ArrayW<::StringW> blendShapeNames,
                                                                                                   ::ArrayW<::GlobalNamespace::OVRFaceExpressions_FaceExpression> faceExpressions,
                                                                                                   bool allowDuplicateMapping);

  /// @brief Method AutoMapBlendshapes, addr 0x5ef6cc0, size 0x340, virtual false, abstract: false, final false
  static inline void AutoMapBlendshapes(::GlobalNamespace::OVRCustomFace* customFace);

  /// @brief Method ClearBlendshapes, addr 0x5ef7150, size 0xc0, virtual false, abstract: false, final false
  static inline void ClearBlendshapes(::GlobalNamespace::OVRCustomFace* customFace);

  /// @brief Method CustomAutoGeneratedMapping, addr 0x5ef7108, size 0x48, virtual false, abstract: false, final false
  static inline ::ArrayW<::GlobalNamespace::OVRFaceExpressions_FaceExpression> CustomAutoGeneratedMapping(::GlobalNamespace::OVRCustomFace* customFace, ::UnityEngine::Mesh* sharedMesh,
                                                                                                          bool allowDuplicateMapping);

  /// @brief Method FindBestMatch, addr 0x5ef6740, size 0x3d4, virtual false, abstract: false, final false
  static inline ::GlobalNamespace::OVRFaceExpressions_FaceExpression FindBestMatch(::ArrayW<::System::Collections::Generic::HashSet_1<::StringW>*> tokenizedOptions, ::StringW searchString,
                                                                                   ::ArrayW<::GlobalNamespace::OVRFaceExpressions_FaceExpression> expressions,
                                                                                   ::GlobalNamespace::OVRFaceExpressions_FaceExpression fallback);

  /// @brief Method IsLipsToward, addr 0x5ef6b14, size 0x104, virtual false, abstract: false, final false
  static inline bool IsLipsToward(::StringW blendshapeName);

  /// @brief Method OculusFaceAutoGenerateMapping, addr 0x5ef7000, size 0x108, virtual false, abstract: false, final false
  static inline ::ArrayW<::GlobalNamespace::OVRFaceExpressions_FaceExpression> OculusFaceAutoGenerateMapping(::UnityEngine::Mesh* sharedMesh, bool allowDuplicateMapping);

  /// @brief Method SplitCamelCase, addr 0x5ef6c18, size 0xa8, virtual false, abstract: false, final false
  static inline ::StringW SplitCamelCase(::StringW input);

  /// @brief Method TokenizeString, addr 0x5ef6208, size 0x538, virtual false, abstract: false, final false
  static inline ::System::Collections::Generic::HashSet_1<::StringW>* TokenizeString(::StringW s);

protected:
  // Ctor Parameters []
  // @brief default ctor
  constexpr OVRCustomFaceExtensions();

public:
  // Ctor Parameters [CppParam { name: "", ty: "OVRCustomFaceExtensions", modifiers: "&&", def_value: None }]
  // @brief delete move ctor to prevent accidental deref moves
  OVRCustomFaceExtensions(OVRCustomFaceExtensions&&) = delete;

  // Ctor Parameters [CppParam { name: "", ty: "OVRCustomFaceExtensions", modifiers: "const&", def_value: None }]
  // @brief delete copy ctor to prevent accidental deref copies
  OVRCustomFaceExtensions(OVRCustomFaceExtensions const&) = delete;

  /// @brief IL2CPP Metadata Type Index
  static constexpr uint32_t __IL2CPP_TYPE_DEFINITION_INDEX{ 7847 };

  static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(sizeof(::GlobalNamespace::OVRCustomFaceExtensions) == 0x10, "Size mismatch!");

} // namespace GlobalNamespace
