#pragma once
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualInt64_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualInt64_impl.hpp"
#endif
