#pragma once
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualDouble_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualDouble_impl.hpp"
#endif
