#pragma once
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualUInt16_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualUInt16_impl.hpp"
#endif
