#pragma once
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualSingle_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualSingle_impl.hpp"
#endif
