#pragma once
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualInt32_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Linq/Expressions/Interpreter/zzzz__GreaterThanOrEqualInstruction_GreaterThanOrEqualInt32_impl.hpp"
#endif
