#ifdef __cpp_modules
module;
#endif

#pragma once
#include "Newtonsoft/Json/Utilities/AotHelper.hpp"
#include "Newtonsoft/Json/Utilities/AsyncUtils.hpp"
#include "Newtonsoft/Json/Utilities/Base64Encoder.hpp"
#include "Newtonsoft/Json/Utilities/BidirectionalDictionary_2.hpp"
#include "Newtonsoft/Json/Utilities/BoxedPrimitives.hpp"
#include "Newtonsoft/Json/Utilities/BufferUtils.hpp"
#include "Newtonsoft/Json/Utilities/CollectionUtils.hpp"
#include "Newtonsoft/Json/Utilities/CollectionWrapper_1.hpp"
#include "Newtonsoft/Json/Utilities/ConvertUtils.hpp"
#include "Newtonsoft/Json/Utilities/Creator_1.hpp"
#include "Newtonsoft/Json/Utilities/DateTimeParser.hpp"
#include "Newtonsoft/Json/Utilities/DateTimeUtils.hpp"
#include "Newtonsoft/Json/Utilities/DictionaryWrapper_2.hpp"
#include "Newtonsoft/Json/Utilities/DynamicProxyMetaObject_1.hpp"
#include "Newtonsoft/Json/Utilities/DynamicProxy_1.hpp"
#include "Newtonsoft/Json/Utilities/DynamicUtils.hpp"
#include "Newtonsoft/Json/Utilities/EnumInfo.hpp"
#include "Newtonsoft/Json/Utilities/EnumUtils.hpp"
#include "Newtonsoft/Json/Utilities/FSharpFunction.hpp"
#include "Newtonsoft/Json/Utilities/FSharpUtils.hpp"
#include "Newtonsoft/Json/Utilities/IWrappedCollection.hpp"
#include "Newtonsoft/Json/Utilities/IWrappedDictionary.hpp"
#include "Newtonsoft/Json/Utilities/ImmutableCollectionsUtils.hpp"
#include "Newtonsoft/Json/Utilities/JavaScriptUtils.hpp"
#include "Newtonsoft/Json/Utilities/JsonTokenUtils.hpp"
#include "Newtonsoft/Json/Utilities/LateBoundReflectionDelegateFactory.hpp"
#include "Newtonsoft/Json/Utilities/MathUtils.hpp"
#include "Newtonsoft/Json/Utilities/MethodCall_2.hpp"
#include "Newtonsoft/Json/Utilities/MiscellaneousUtils.hpp"
#include "Newtonsoft/Json/Utilities/NoThrowExpressionVisitor.hpp"
#include "Newtonsoft/Json/Utilities/NoThrowGetBinderMember.hpp"
#include "Newtonsoft/Json/Utilities/NoThrowSetBinderMember.hpp"
#include "Newtonsoft/Json/Utilities/ParseResult.hpp"
#include "Newtonsoft/Json/Utilities/ParserTimeZone.hpp"
#include "Newtonsoft/Json/Utilities/PrimitiveTypeCode.hpp"
#include "Newtonsoft/Json/Utilities/ReflectionDelegateFactory.hpp"
#include "Newtonsoft/Json/Utilities/ReflectionMember.hpp"
#include "Newtonsoft/Json/Utilities/ReflectionObject.hpp"
#include "Newtonsoft/Json/Utilities/ReflectionUtils.hpp"
#include "Newtonsoft/Json/Utilities/StringBuffer.hpp"
#include "Newtonsoft/Json/Utilities/StringReference.hpp"
#include "Newtonsoft/Json/Utilities/StringReferenceExtensions.hpp"
#include "Newtonsoft/Json/Utilities/StringUtils.hpp"
#include "Newtonsoft/Json/Utilities/StructMultiKey_2.hpp"
#include "Newtonsoft/Json/Utilities/ThreadSafeStore_2.hpp"
#include "Newtonsoft/Json/Utilities/TypeExtensions.hpp"
#include "Newtonsoft/Json/Utilities/TypeInformation.hpp"
#include "Newtonsoft/Json/Utilities/ValidationUtils.hpp"
#ifdef __cpp_modules
export module Utilities;
#endif
