#ifdef __cpp_modules
module;
#endif

#pragma once
#include "UnityEngine/Rendering/UnifiedRayTracing/AccelStructAdapter.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/AccelStructInstances.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/AccelerationStructureOptions.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/AsyncTerrainToMeshRequest.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/BLASPositionsPool.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/BackendHelpers.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/BlockAllocator.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/BuildFlags.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/ComputeRayTracingAccelStruct.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/ComputeRayTracingBackend.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/ComputeRayTracingShader.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/ComputeTerrainMeshJob.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeoPoolMeshChunk.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeoPoolVertex.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeoPoolVertexAttribs.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPool.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolConstants.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolDesc.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolEntryDesc.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolEntryInfo.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolHandle.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GeometryPoolSubmeshData.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/GraphicsHelpers.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/HardwareRayTracingAccelStruct.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/HardwareRayTracingBackend.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/HardwareRayTracingShader.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/IRayTracingAccelStruct.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/IRayTracingBackend.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/IRayTracingShader.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/MeshInstanceDesc.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/PersistentGpuArray_1.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/RayTracingBackend.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/RayTracingContext.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/RayTracingHelper.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/RayTracingRenderPipelineResources.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/RayTracingResources.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/ReferenceCounter.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/SID.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/TerrainDesc.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/TerrainToMesh.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/UnifiedRayTracingError.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/UnifiedRayTracingException.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/Utils.hpp"
#include "UnityEngine/Rendering/UnifiedRayTracing/VertexBufferChunk.hpp"
#ifdef __cpp_modules
export module UnifiedRayTracing;
#endif
