#pragma once
#include "Unity/Collections/LowLevel/Unsafe/zzzz__NativeContainerSupportsMinMaxWriteRestrictionAttribute_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Unity/Collections/LowLevel/Unsafe/zzzz__NativeContainerSupportsMinMaxWriteRestrictionAttribute_impl.hpp"
#endif
