#pragma once
#include "Unity/Collections/LowLevel/Unsafe/zzzz__NativeContainerSupportsDeallocateOnJobCompletionAttribute_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Unity/Collections/LowLevel/Unsafe/zzzz__NativeContainerSupportsDeallocateOnJobCompletionAttribute_impl.hpp"
#endif
