#pragma once
#include "System/Threading/zzzz__CancellationTokenSource_Linked1CancellationTokenSource_def.hpp"
#include "System/Threading/zzzz__CancellationTokenSource_Linked1CancellationTokenSource_impl.hpp"
