#pragma once
#include "System/Threading/zzzz__CancellationTokenSource_Linked2CancellationTokenSource_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Threading/zzzz__CancellationTokenSource_Linked2CancellationTokenSource_impl.hpp"
#endif
