#pragma once
#include "System/Threading/zzzz__CancellationTokenSource_Linked1CancellationTokenSource_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "System/Threading/zzzz__CancellationTokenSource_Linked1CancellationTokenSource_impl.hpp"
#endif
