#ifdef __cpp_modules
module;
#endif

#pragma once
#include "OculusStudios/GraphQL/Client/ClientExtensions.hpp"
#include "OculusStudios/GraphQL/Client/ConcreteConverter_1.hpp"
#include "OculusStudios/GraphQL/Client/ConcreteListConverter_2.hpp"
#include "OculusStudios/GraphQL/Client/DateTimeConverter.hpp"
#include "OculusStudios/GraphQL/Client/EnumConverter_1.hpp"
#include "OculusStudios/GraphQL/Client/EnumListConverter_1.hpp"
#include "OculusStudios/GraphQL/Client/FBUserAgent.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLClient.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLClientConfigException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLClientInfraException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLConnectivityException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLError.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLErrorException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLLiveQuery.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLModel.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLMutation.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLMutationOperation.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLOperationBase.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLQuery.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLQueryOperation.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLRequest.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLRequestException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLRequestExceptionRateLimitExceeded.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLResponse.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLResponseParseException.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLResponseStream.hpp"
#include "OculusStudios/GraphQL/Client/GraphQLUtils.hpp"
#include "OculusStudios/GraphQL/Client/HttpHeaderConstants.hpp"
#include "OculusStudios/GraphQL/Client/HttpPersistentTransport.hpp"
#include "OculusStudios/GraphQL/Client/HttpPollingTransport.hpp"
#include "OculusStudios/GraphQL/Client/HttpRequestManager.hpp"
#include "OculusStudios/GraphQL/Client/HttpTransport.hpp"
#include "OculusStudios/GraphQL/Client/IFragment.hpp"
#include "OculusStudios/GraphQL/Client/IGraphQLClientTransport.hpp"
#include "OculusStudios/GraphQL/Client/MinimalMainThreadExecutor.hpp"
#include "OculusStudios/GraphQL/Client/MultipartFile.hpp"
#include "OculusStudios/GraphQL/Client/MutationRequest.hpp"
#include "OculusStudios/GraphQL/Client/MutationRequest_1.hpp"
#include "OculusStudios/GraphQL/Client/NestedFragmentConverter_1.hpp"
#include "OculusStudios/GraphQL/Client/NestedFragmentListConverter_1.hpp"
#include "OculusStudios/GraphQL/Client/PreserveAttribute.hpp"
#include "OculusStudios/GraphQL/Client/QueryRequest.hpp"
#include "OculusStudios/GraphQL/Client/ResponsePayload.hpp"
#ifdef __cpp_modules
export module Client;
#endif
