#pragma once
#include "BeatmapDataLoaderVersion4/zzzz__LightRotationEventBoxGroupConverter_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "BeatmapDataLoaderVersion4/zzzz__LightRotationEventBoxGroupConverter_impl.hpp"
#endif
