#pragma once
#include "BeatmapDataLoaderVersion4/zzzz__LightColorEventBoxGroupConverter_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "BeatmapDataLoaderVersion4/zzzz__LightColorEventBoxGroupConverter_impl.hpp"
#endif
