#ifdef __cpp_modules
module;
#endif

#pragma once
#include "UnityEngine/UIElements/Layout/ComponentType.hpp"
#include "UnityEngine/UIElements/Layout/FixedBuffer16_1.hpp"
#include "UnityEngine/UIElements/Layout/FixedBuffer2_1.hpp"
#include "UnityEngine/UIElements/Layout/FixedBuffer9_1.hpp"
#include "UnityEngine/UIElements/Layout/ILayoutProcessor.hpp"
#include "UnityEngine/UIElements/Layout/InvokeBaselineFunctionDelegate.hpp"
#include "UnityEngine/UIElements/Layout/InvokeMeasureFunctionDelegate.hpp"
#include "UnityEngine/UIElements/Layout/LayoutAlign.hpp"
#include "UnityEngine/UIElements/Layout/LayoutBaselineFunction.hpp"
#include "UnityEngine/UIElements/Layout/LayoutCacheData.hpp"
#include "UnityEngine/UIElements/Layout/LayoutCachedMeasurement.hpp"
#include "UnityEngine/UIElements/Layout/LayoutComputedData.hpp"
#include "UnityEngine/UIElements/Layout/LayoutConfig.hpp"
#include "UnityEngine/UIElements/Layout/LayoutConfigData.hpp"
#include "UnityEngine/UIElements/Layout/LayoutConfigDataType.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDataAccess.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDataStore.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDefaults.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDelegates.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDirection.hpp"
#include "UnityEngine/UIElements/Layout/LayoutDisplay.hpp"
#include "UnityEngine/UIElements/Layout/LayoutEdge.hpp"
#include "UnityEngine/UIElements/Layout/LayoutFlexDirection.hpp"
#include "UnityEngine/UIElements/Layout/LayoutHandle.hpp"
#include "UnityEngine/UIElements/Layout/LayoutJustify.hpp"
#include "UnityEngine/UIElements/Layout/LayoutList_1.hpp"
#include "UnityEngine/UIElements/Layout/LayoutManager.hpp"
#include "UnityEngine/UIElements/Layout/LayoutMeasureFunction.hpp"
#include "UnityEngine/UIElements/Layout/LayoutMeasureMode.hpp"
#include "UnityEngine/UIElements/Layout/LayoutNative.hpp"
#include "UnityEngine/UIElements/Layout/LayoutNode.hpp"
#include "UnityEngine/UIElements/Layout/LayoutNodeData.hpp"
#include "UnityEngine/UIElements/Layout/LayoutNodeDataType.hpp"
#include "UnityEngine/UIElements/Layout/LayoutOverflow.hpp"
#include "UnityEngine/UIElements/Layout/LayoutPositionType.hpp"
#include "UnityEngine/UIElements/Layout/LayoutProcessor.hpp"
#include "UnityEngine/UIElements/Layout/LayoutProcessorNative.hpp"
#include "UnityEngine/UIElements/Layout/LayoutSize.hpp"
#include "UnityEngine/UIElements/Layout/LayoutState.hpp"
#include "UnityEngine/UIElements/Layout/LayoutStyleData.hpp"
#include "UnityEngine/UIElements/Layout/LayoutUnit.hpp"
#include "UnityEngine/UIElements/Layout/LayoutValue.hpp"
#include "UnityEngine/UIElements/Layout/LayoutWrap.hpp"
#include "UnityEngine/UIElements/Layout/ManagedObjectStore_1.hpp"
#ifdef __cpp_modules
export module Layout;
#endif
